### ISSUE TITLE
[Question] explanation on faults

### ISSUE THREAD

**Issue by andrea-bistacchi** [Loop3D/LoopStructural#105]
Hi, and thanks for all your work as usual!

I'm trying to figure out how faults work. It looks like something is changing here.

I summarize what I think I understood:

1) First you must instantiate a fault frame with `FaultBuilder()`. The only required parameter is the `model`, while `interpolator`, `interpolators`, and `fault_bounding_box_buffer` are not mandatory.

- I do not understand the difference between `interpolator` and `interpolators`.

- How does `fault_bounding_box_buffer` work? In the code comments you say "the maximum area around the model domain that a fault is modelled." so it looks like the fault will extend out of the modelling domain? Or you mean an extension with respect to the fault data bounding box?

- Is it necessary to instantiate like this, or calling the function below is enough?

2) Then you must specify some data, and particularly the slip vector and slip modulus. I understand this is done with `FaultBuilder.create_data_from_geometry()`.

- Here `data` is the model dataframe, so the same as `model` in `FaultBuilder()`?

- All other parameters except `slip_vector` are generated automatically from data (e.g. the fault trace) if not specified, correct?

Thanks very much!

**Comment by lachlangrose** [comment]
Hi Andrea, 

I'll try to answer your questions.

1. A fault is represented by the curvilinear fault frame. This can be built using the FaultBuilder, the fault builder needs to have either an interpolator e.g. fdi or pli, or have a list of interpolators to use a different one for each field of the fault frame. It should throw an exception "Missing interpolator" if you try to add a fault without an interpolator or interpolators specified.
* Interpolator uses the same type of interpolator for all fields, interpolators defines each interpolator separately in a list. This is more for folds but may be useful for faults down the road.
* For finite faults, the fault is only interpolated within the volume where the fault faults other geological features. This is to save time interpolating the faults everywhere. The fault_bounding_box_buffer adds a small region around the bounding box defined by the map pattern to make sure that the scalar fields are defined everywhere they need to be.

2. The create_data_from_geometry() method creates the required data using assumptions about the fault slip and orientation of the fault frame. If you don't want to control the specifics of the fault geometry it is ok to use this.
* The data is a slice of the model dataframe that only includes the data points relevant to that fault.
* Yeah that is correct.

I'm not sure how you are using LoopStructural currently but if its possible I would recommend trying to interface with LoopStructural using the GeologicalModel class for adding features. So in this case you would use GeologicalModel.create_and_add_fault instead of manually creating the fault objects. 

I will try to make sure that the main API through the GeologicalModel class always works and will try to limit any changes to syntax. This won't be the case for using the classes in another way. If there is something missing from the create_and_add_fault method let me know and I can add the options into this code. 

Cheers,

Lachlan

**Comment by andrea-bistacchi** [comment]
Hi and thanks!

More clear now. I was looking into the wrong module.

Regarding slip_vector and displacement, the first is a unit vector, and the second is its magnitude, correct? Is there a way to estimate them from data or they must always be specified?

**Comment by lachlangrose** [comment]
Hi Andrea,

I am working on ways to estimate them from data but as you can imagine its not a simple problem. For now it is best to just estimate them from data.

Cheers

**Comment by andrea-bistacchi** [comment]
Ok, makes sense! Better a simple solution that works than a complex one that might not work...

Thanks!

**Comment by lachlangrose** [comment]
Yeah. It depends on the type of dataset you have. If you are looking at purely map view then we have the map2loop library which can estimate displacements from the map, but for now that assumes vertical displacement.
