### ISSUE TITLE
inconsistency between origin, maximal extent and bounding box

### ISSUE THREAD

**Issue by gpirot** [Loop3D/LoopStructural#109]
### Describe your issue

Hi Lachlan,
When specifying the model dimensions `model = GeologicalModel([xmin,ymin,zmin],[xmax,ymax,zmax])`
with an origin different than [0,0,0], LoopStructural seems to shift the origin of the bounding box to [0,0,0].

Example:
Bounding Box values:
[[ 0.  0.  0.]
 [10.  4.  6.]]
Defined Model Extent values:
[[ 2  0 -6]
 [12  4  0]]

Though it does not impact the input data considered for modelling, it affects the evaluation of the model (e.g. `evaluate_model()` or `calculate_fault_topology_matrix(model,xyz)`) at xyz locations, that apparently have to be rescaled accordingly with the extent of the bounding box and not the initially defined extent.

[boudingbox-vs-modelextent.zip](https://github.com/Loop3D/LoopStructural/files/8094337/boudingbox-vs-modelextent.zip)

### Minimal reproducing code example

```python
see example in notebook above for impact on the `evaluate_model` function
```

### Error message

```shell
None
```

**Comment by lachlangrose** [comment]
Hi Guillaume,

Can you please stop submitting bug requests with zip files rather than a **minimal reproducing code example**. There are a few reasons for this:
1. You might discover the cause of the bug while trying to recreate a minimal working example. For example your previous issue with the pandas datatypes.
2. Code included in the issue is searchable so if someone has the same error or the same code it will appear in the search engine, if its in a zip file I doubt it.
3. It is easier for me to answer issues if I can see the code rather than having to run the code myself. I can also use a github action to automatically run the code to test whether the issue occurs on more than one OS.

To demonstrate what I mean by a minimal working example I will make one for this issue.

```
from LoopStructural import GeologicalModel
from LoopStructural.datasets import load_claudius

# use claudius example dataset
data, bb = load_claudius()
## origin is not [0,0,0]
print(bb)
model = GeologicalModel(bb[0,:],bb[1,:])
model.data = data
model.create_and_add_foliation('strati')
# use stratigraphic column from example 1.d
stratigraphic_column = {}
stratigraphic_column['strati'] = {}
stratigraphic_column['strati']['unit2'] = {'min':0,'max':60,'id':1}
stratigraphic_column['strati']['unit3'] = {'min':60,'max':250,'id':2}
stratigraphic_column['strati']['unit4'] = {'min':250,'max':330,'id':3}
stratigraphic_column['strati']['unit5'] = {'min':330,'max':-np.inf,'id':4}
model.stratigraphic_column = stratigraphic_column

[[xminbb,yminbb,zminbb],[xmaxbb,ymaxbb,zmaxbb]] = model.bounding_box
# create a list of xyz locations using meshgrid
eval_pts = np.array(np.meshgrid(np.linspace(xminbb, xmaxbb, 10),np.linspace(yminbb, ymaxbb, 10),np.linspace(zminbb, zmaxbb, 10))).T.reshape(-1,3)
# get ls-evaluated-model
lithos_model_bounding_box = model.evaluate_model(eval_pts,scale=False)
[[xminbb,yminbb,zminbb],[xmaxbb,ymaxbb,zmaxbb]] = bb#model.bounding_box
# create a list of xyz locations using meshgrid
eval_pts2 = np.array(np.meshgrid(np.linspace(xminbb, xmaxbb, 10),np.linspace(yminbb, ymaxbb, 10),np.linspace(zminbb, zmaxbb, 10))).T.reshape(-1,3)
# get ls-evaluated-model
print('Print model.evaluate_model scale=False')
lithos_input_bounding_box = model.evaluate_model(eval_pts2,scale=False)
print(f"All points are the same: {np.all(np.isclose(lithos_model_bounding_box-lithos_input_bounding_box,0))}")
print('Print model.evaluate_model scale=True')
lithos_input_bounding_box_scale_true = model.evaluate_model(eval_pts2,scale=True)
print(f"All points are the same: {np.all(np.isclose(lithos_model_bounding_box-lithos_input_bounding_box_scale_true,0))}")
```

As for this issue, I would not label it a bug as LoopStructural is performing as intended, it is probably a lack of documentation. The model is translated to have an origin of 0,0,0 to avoid any potential numerical errors. If you call model.evaluate_model(xyz,scale=True) with points the points will be scaled into the model coordinate system. If you call with scale=False it will not scale the points into the model coordinate system. 

As for the issue with the topology matrix, I will add an argument to rescale the points but be aware all of the functions in the analysis module have been created as proof of concepts. 

I am going to relabel this issue as a documentation problem and you are welcome to submit a pull request with changes to the documentation.

Cheers

**Comment by gpirot** [comment]
Hi Lachlan,

Thanks for these explanations. And my apologies if my self-contained example formatted in a python notebook (which cannot be uploaded directly, thus zipped) was not meeting your formatting expectations.

Cheers
