### ISSUE TITLE
[Question] extrapolate fault surface as arc / curve away from control

### ISSUE THREAD

**Issue by GeoMattB** [Loop3D/LoopStructural#134]
Is it possible to build a fault surface using the surface and seismic trace x,y,z that trends as an arc or curve rather than a straight line based on the gradient?

**Comment by lachlangrose** [comment]
Hi Matt,

If you have a seismic interpretation that trends as an arc then your gradient measurement only needs to be the local orientation of the surface. So if you have surface observations of the fault you could use these or just estimate it from the seismic interpretation. Does this help?

Cheers,

Lachlan

**Comment by GeoMattB** [comment]
Hi Lachlan,
I've attached what we're using to create a surface. 
What we're trying to do have the fault behave more like it does at the seismic intersection, and interpolate that along its length rather than just use the gradient away from the data point. 
[Avoca_Fault_as_curved_surface.zip](https://github.com/Loop3D/LoopStructural/files/10080218/Avoca_Fault_as_curved_surface.zip)

**Comment by lachlangrose** [comment]
I think there are two things here. 

1. Calculating the dip vector of a curved line is not idea, it would be better to segment the line into sections and have local orientation constraints for this. 
2. The orientation measurement is a long way from the fault surface

![image](https://user-images.githubusercontent.com/7371904/203682545-55ac4a99-ea16-4917-9c6c-03792f760f36.png)

To make the point appear on the fault, it would be better to choose to locate it either on the seismic line or on the fault trace:
```
ori['X'] = Avoca_Fault_seismic['X'].mean()
ori['Y'] = Avoca_Fault_seismic['Y'].mean()
ori['Z'] = Avoca_Fault_seismic['Z'].mean()
```
```
ori['X'] = Avoca_Fault_surface['X'].mean()
ori['Y'] = Avoca_Fault_surface['Y'].mean()
ori['Z'] = Avoca_Fault_surface['Z'].mean()
```

So the orientation data would look something like this if we make it on the seismic section.

![image](https://user-images.githubusercontent.com/7371904/203682945-47d50ad2-985a-4a7f-8216-8772b80f8934.png)

If you segment the line and add gradient constraints for each segment you can get 
![image](https://user-images.githubusercontent.com/7371904/203686160-bbe90fa6-acb8-47ea-b3a2-8a6bb0c466e2.png)

I modified the code in your notebook
`
segments = 5
cps=[]
segment_size = -(Avoca_Fault_seismic['Z'].max()-Avoca_Fault_seismic['Z'].min())/segments
for _ in range(segments):
    
    min_xy = Avoca_Fault_surface[["X", "Y", "Z"]].to_numpy()[0, :]
    max_xy = Avoca_Fault_surface[["X", "Y", "Z"]].to_numpy()[-1, :]
    
    maxz = _*segment_size+Avoca_Fault_surface['Z'].max()
    minz = _*segment_size+segment_size+Avoca_Fault_seismic['Z'].max()
    tangent_xy = max_xy - min_xy
    tangent_xy /= np.linalg.norm(tangent_xy)
    seismic_slice = Avoca_Fault_seismic.loc[np.logical_and(Avoca_Fault_seismic['Z']>minz,Avoca_Fault_seismic['Z']<maxz),:]
    if seismic_slice.shape[0]>0:
        max_z = seismic_slice[seismic_slice['Z']==seismic_slice['Z'].max()][['X', 'Y', 'Z']].to_numpy()
        min_z = seismic_slice[seismic_slice['Z']==seismic_slice['Z'].min()][['X', 'Y', 'Z']].to_numpy()

        tangent_z1 = (max_z - min_z)
        if  np.linalg.norm(tangent_z1)>0:
            
            tangent_z1 /= np.linalg.norm(tangent_z1)
            vector = np.cross(tangent_xy,tangent_z1)
            cps.append(vector[0].tolist()+seismic_slice[['X','Y','Z']].mean().tolist()+['Avoca_Fault'])
       

ori = pd.DataFrame(CP)
ori['fault_name'] = "Avoca_Fault"
ori.columns = ['gx', 'gy', 'gz', 'fault_name']

ori['X'] = Avoca_Fault_seismic['X'].mean()
ori['Y'] = Avoca_Fault_seismic['Y'].mean()
ori['Z'] = Avoca_Fault_seismic['Z'].mean()

ori = pd.DataFrame(cps, columns=[ 'gx', 'gy', 'gz','X', 'Y', 'Z', 'fault_name'])
`

But this doesn't actually fix the problem, because the depth geometry data is all concentrated along a single siesmic section. One way to fix this is add an additional constraint, an anisotropy, that will make the gradient of the interpolated scalar field orthogonal to the vector. If we use the fault trace to define the vector, it means that the surface will fit the gradient constraints, the fault location as well as making sure the gradient of the interpolated scalar field is orthogonal to the strike vector from the fault.

![image](https://user-images.githubusercontent.com/7371904/203687609-d7399e52-b918-400e-84d7-e84a5157c30e.png)

The code to do this is pretty simple in loopstructural

```
from LoopStructural.modelling.features import AnalyticalGeologicalFeature
anisotropy = AnalyticalGeologicalFeature('name',tangent_xy,np.zeros(3)) #use tangent xy to constrain the fault trace anisotropy
processor2 = ProcessInputData(fault_locations = all_avoca, fault_orientations = ori,
                             origin=origin, maximum=maximum)

model2 = GeologicalModel(origin, maximum)

model2.data = processor2.data

model2.create_and_add_fault('Avoca_Fault', interpolatortype='PLI', displacement = 100, nelements=1e4, force_mesh_geometry = False, cpw=1)
model2['Avoca_Fault'][0].builder.add_orthogonal_feature(anisotropy) #add the anisotropy to the fault
model2.update()
```

**Comment by GeoMattB** [comment]
Thanks Lachlan, that works and is exactly what we want to do, awesome!
