### ISSUE TITLE
[Question] vocabulary / rdf 

### ISSUE THREAD

**Issue by GeoMattB** [Loop3D/LoopStructural#136]
Hi Loopers,
Does LoopStructural connect to the vocabularies or use a syntax that's compatible?
Or, would we need to parse a vocabulary with a bit of translation between?

Thanks

**Comment by lachlangrose** [comment]
Hi @GeoMattB, can you clarify what you mean by vocabularies please?

**Comment by lachlangrose** [comment]
Ok no LoopStructural doesn't connect to the vocabularies currently. There is no reason why it can't if there is a use case for it, I think once there are datasets in this format it will be easier to work out how to use them in m2l and LS.

**Comment by GeoMattB** [comment]
I'm looking at the abutting relationships for the Kalgoorlie fault model @AngRodrigues put together for the GA workshop as an example. Ideally we'd have a way to capture & store those types of relationships efficiently and the vocabs seem to be the way everyone is going.
Thanks

**Comment by lachlangrose** [comment]
There is an input format for the fault relationships in LoopStructural. See https://loop3d.github.io/LoopStructural/_auto_examples/3_fault/plot_fault_network.html#sphx-glr-auto-examples-3-fault-plot-fault-network-py
```
ProcessInputData(
    fault_orientations=ori,
    fault_locations=df,
    origin=origin,
    maximum=maximum,
    fault_edges=[("fault_2", "fault_1")],
    fault_edge_properties=[{"angle": 10}],
)
```
You put the link between faults in the fault_edges and the an abutting relationship occurs when the angle is less than 30 degrees. Otherwise, it's modelled as a splay. This format was really just designed as a way to use the map2loop fault data. But effectively it is a graph where the nodes are the faults and the edges define the relationship and we can have properties on both the nodes and on the edges. 

I think the ontology/vocabulary that LoopStructural uses will need to be a subset of the ontology that is proposed by the GKM. So we will need to have a translator to extract and simplify everything to the relevant format. @GeoMattB do you think you will generate an example dataset in the foreseeable future? it would be great to try and make this link work.

**Comment by GeoMattB** [comment]
"do you think you will generate an example dataset in the foreseeable future? it would be great to try and make this link work."
Short answer : yes. I've got a little time to dig into this.

**Comment by GeoMattB** [comment]
I'm going to need to back off from my earlier enthusiasm about the vocabs / ttf formats for the moment. I don't have an easy way to generate the .ttf vocabulary files. I should be able to build a set of tables (sqlite / gpkg from within QGIS is probably easy) where I can build the attributes and have rdf style triples for the faults. This *should capture the relationships correctly.
