### ISSUE TITLE
[FEATURE] Support for Python 3.10

### ISSUE THREAD

**Issue by SamuelBradley** [Loop3D/LoopStructural#139]
**Is your feature request related to a problem? Please describe.**
Loop Structural currently does not build for Python310 and fails when attempting to build from source (via pypi) in a python 310 environment. 

**Describe the solution you'd like**
Loop structural should release to pypi with wheels built for python 310 in order to support its use in larger Jupyter hub images that currently use python 310 (EASI Hub specifically)

**Describe alternatives you've considered**
It may be possible to build from git rather than pypi in a python310 environment i.e. 
`pip install git+https://github.com/Loop3D/LoopStructural.git`
But this is not an ideal solution when 310 support appears to be relatively straight forward.  (I have verified the tests pass in a fresh 310 environment)

**Comment by lachlangrose** [comment]
Hi @SamuelBradley ,

I can add python 3.10 support, there is no reason its not there other than me being slow to update the build files!

Cheers,

Lachlan

**Comment by SamuelBradley** [comment]
Thanks, that would help us out a lot, we are trying to integrate it into our Jupyter Hub image which recently upgrade to Python 310.

**Comment by lachlangrose** [comment]
Are you using Lavavu? I have been having trouble with lavavu-osmesa versions, and I imagine if its jupyter hub you'll need the headless version?

**Comment by HUN220** [comment]
Hi @lachlangrose, I work with Sam and I've been able to get `LoopStructural` and `lavavu-osmesa` working with our JupyterLabs environment with mixed success. In my requirements.txt I've just got:
```
LoopStructural@git+https://github.com/Loop3D/LoopStructural.git
lavavu-osmesa
```

I initially used `lavavu` which obviously didn't work headless ("X server not found" errors I think it was). After switching to `lavavu-osmesa` I needed to include the lavavu_osmesa.libs directory in LD_LIBRARY_PATH for it to work. e.g. `ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/env/lib/python3.10/site-packages/lavavu_osmesa.libs`. Note that you need to define LD_LIBRARY_PATH prior to starting your python environment.

**Environment:**
- Python: 3.10.6
- libgl1: 1.4.0-1 (apt install into Ubuntu 22.04.1 LTS) 
- Cython: 0.29.33
- lavavu-osmesa: 1.8.36
- LoopStructural: 1.5.3 (via git source)
- numpy: 1.22.4

Most examples from the docs I've tested appear to work now however `LoopStructural.modelling.ProcessInputData` seems to have issues with example 3b (Modelling a fault network in LoopStructural). The setter for `fault_locations` doesn't appear to trigger when creating the `ProcessInputData` instance which has the follow on effect of the "feature_name" key not being present when `ProcessInputData.__init__` attempts to create the df for `self.fault_properties`.

```python
        self._fault_properties = None
        if fault_properties is not None:
            self.fault_properties = fault_properties
        elif fault_locations is not None:
            self.fault_properties = pd.DataFrame(
                self.fault_locations["feature_name"].unique(), columns=["name"]
            ).set_index("name")
```

I think something must be off when I'm building `LoopStructural` from source because it all works locally, and if I manually define the `ProcessInputData` class in the notebook instead of importing it then it works fine. Weird.

**Comment by lachlangrose** [comment]
Hi @SamuelBradley ,

I've pushed LoopStructural for python 3.10 to pypi, and also pushed the source files to pypi so it should work with pip install even if there is no wheel available.

Let me know if it works for you. I have to update conda still, but that will be done soon. 

Cheers

**Comment by SamuelBradley** [comment]
Thanks @lachlangrose much appreciated.

**Comment by HUN220** [comment]
@lachlangrose, confirming that `LoopStructural-1.5.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` successfully installs for us via PyPI. 

Thanks very much for adding python 3.10 support!
