### ISSUE TITLE
Fault ellipse

### ISSUE THREAD

**Issue by kerrybardot** [Loop3D/LoopStructural#147]
Hello! Trying to model a finite fault with ellipse displacement using the parameters located here:

https://loop3d.github.io/LoopStructural/user_guide/fault_modelling.html

Please see my parameters and the result. My fault is still infinite in the horizontal and vertical plane - any suggestions?

![image](https://user-images.githubusercontent.com/65206513/222632699-e2aacef3-c0bc-4b45-838d-059454657991.png)

![image](https://user-images.githubusercontent.com/65206513/222632990-c60b774e-ee6b-4fb2-b4a7-87ee286f51d1.png)

**Comment by lachlangrose** [comment]
Hi @kerrybardot, 

If you try changing the parameters to be very small relative to the size of the model does it work? Alternatively, could you make a minimal working example to demonstrate the issue that I can run 

Cheers

**Comment by kerrybardot** [comment]
Hi @lachlangrose 
Thanks for getting back to me... I still can't figure it out. I want to see an offset in the middle of the fault but not reaching to surface.  Have tried tweaking fault parameters but can't seem to make it work. Please see my code!
Kerry

[fault_ellipse.zip](https://github.com/Loop3D/LoopStructural/files/10910289/fault_ellipse.zip)

**Comment by lachlangrose** [comment]
Hi,

I had a look at the model today and found a couple of things. 

The "BaseFault" fault function in LoopStructural actually doesn't include the vertical component... I think I removed it because it was unusual that we actually have constraints for the center of the fault in z. I will add an alternative fault function that includes this, but in the meantime you can use:

```Python
from LoopStructural.modelling.features.fault._fault_function import CubicFunction, FaultDisplacement, Composite
hw = CubicFunction()
hw.add_cstr(0, 1)
hw.add_grad(0, 0)
hw.add_cstr(1, 0)
hw.add_grad(1, 0)
hw.add_max(1)
fw = CubicFunction()
fw.add_cstr(0, -1)
fw.add_grad(0, 0)
fw.add_cstr(-1, 0)
fw.add_grad(-1, 0)
fw.add_min(-1)
gyf = CubicFunction()
gyf.add_cstr(-1, 0)
gyf.add_cstr(1, 0)
gyf.add_cstr(-0.2, 1)
gyf.add_cstr(0.2, 1)
gyf.add_grad(0, 0)
gyf.add_min(-1)
gyf.add_max(1)
gzf = CubicFunction()
gzf.add_cstr(-1, 0)
gzf.add_cstr(1, 0)
gzf.add_cstr(-0.2, 1)
gzf.add_cstr(0.2, 1)
gzf.add_grad(0, 0)
gzf.add_min(-1)
gzf.add_max(1)
gxf = Composite(hw, fw)
fault_displacement = FaultDisplacement(gx=gxf, gy=gyf, gz=gzf)
faultfunction = fault_displacement
```

This just makes a fault displacement function with a bell decay profile in the trace/vertical coordinates. 

I updated the fault ellipse argument names to:

- fault_influence -> minor_axis
- fault_extent -> major_axis
- fault_vertical_radius -> intermediate_axis

The old argument names work, except for fault_vertical_radius because of a typo! But if you change to using intermediate_axis then it should work.

If you want to visualise the displacement function in the model you can add the argument `paint_with=model['fault_feature_name'].faultdisplacement`. For example, here I have painted the 0 isosurface of the fault extent field with the displacement.

![image](https://user-images.githubusercontent.com/7371904/223626352-81f4e064-15c6-4324-8ff5-027f46e111e7.png)

Another comment is about how you have constructed your stratigraphic scalar fields, you have used a separate interpolator for each surface but the only constraints you have are for the location of the surface - this results in a badly/unconstrained problem. I would recommend grouping conformable surfaces into the same interpolator/geological feature and then use their thicknesses to determine the stratigraphic value (that you have already calculated). If you don't want to do this, add in some orientation data that constrains the norm of the implicit function gradient.

**Comment by kerrybardot** [comment]
Thanks Lachlan for taking the time to look at my code! Will have a good look at it over the next few days!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lachlangrose** [comment]
@kerrybardot did this solve the problem for you? If so I will close this issue

**Comment by kerrybardot** [comment]
Yes thank you!!
