### ISSUE TITLE
[Question] [Question] Tutorial for Loop3D

### ISSUE THREAD

**Issue by Changwan-planet** [Loop3D/LoopStructural#155]
Dear Loop3D developers,

First of all, thank you for opening this neat program to the world!

I am a graduate student who would like to use loop3D for my research. I have been following your guide in the github or your related homepages.

My question is that how to execute the loop 3D? without any installation?

I read "INSTALL.txt" and installed Qt5, loopprojectfile-cpp, and netCDF-cxx4. I executed some python programs in your download packages, but I cannot start your program.

I also used this command line "bash loop3d.pro",  but I got this error below.

loop3d.pro: line 1: QT: command not found
loop3d.pro: line 2: QT: command not found
loop3d.pro: line 3: QT: command not found
loop3d.pro: line 4: QT: command not found
loop3d.pro: line 5: $'\r': command not found
loop3d.pro: line 7: $'\r': command not found
loop3d.pro: line 8: CONFIG: command not found
loop3d.pro: line 9: $'\r': command not found
loop3d.pro: line 10: win32: command not found
loop3d.pro: line 11: syntax error near unexpected token `release,'
'oop3d.pro: line 11: `    CONFIG(release, debug|release) {

Would you mind sharing any tutorial about loop3D for beginners?
Please help me out!

**Comment by RoyThomsonMonash** [comment]
Thanks for trying out Loop and your interest in using the Loop3D graphical user interface.

We have moved away from using the Loop3D GUI and are looking at using a webapp to make using the Loop libraries more user friendly.  Using a webapp will also give us a simpler avenue to using online servers so that model processing doesn't need to be locally hosted.

Until the webapp is available the best tutorials for using the Loop libraries, in a python environment, are in the Loop3D/map2loop2-notebooks (for map2loop) and the LoopStructural examples (https://loop3d.org/LoopStructural/_auto_examples/index.html) in the LoopStructural documentation.

If you are still interested in the original Loop3D GUI, it is created as a QT project and the loop3d.pro file is the equivalent of a makefile for that project.  To compile it yourself I recommend using Qt Creator.

There is also a Windows compiled version of the Loop3D GUI (and it's python environment) currently hosted on Aarnet under the Monash University tag, however, this requires an Aarnet login and will be taken down at the end of 2023.

**Comment by Changwan-planet** [comment]
Great, nice reply! I wil try the examples in the url. I look forwad to using a webapp-based Loop. 

Thank you for your kind comment.
