### ISSUE TITLE
[BUG] Lavvu conflicts with vtk output

### ISSUE THREAD

**Issue by markjessell** [Loop3D/LoopStructural#34]
**Describe the bug**
Lavavu model does not display in notebook if filename parameter used in view.add_model_surfaces() 
**Minimal working example**

Run a map2loop model with filename paramter in view.add_model_surfaces() 

**Expected behavior**
See lavavu rendered model in notebook

**Screenshots**
see attached
![image](https://user-images.githubusercontent.com/6822240/87011146-1d8d3680-c1fa-11ea-84ef-d9cac1d2c957.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Python environment [anaconda, python3.7]

**Comment by lachlangrose** [comment]
This should be fixed with the most recent version - the issue was some things were being displayed in real world coordinates and others in the scaled model space. I have changed to plot everything in real world coordinates.

Also changed the naming of the surfaces inside lavavu and for the exported file to just use the unit code, not the isovalue.
